"""Tests for SlidingWindow and DataManifest."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pytest

from nexa_backtest.data.schema import IDC_EVENTS_SCHEMA
from nexa_backtest.data.window import DataManifest, RowGroupRef, SlidingWindow
from nexa_backtest.types import HistoricalTrade, MarketDataUpdate

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------

IDC_SCHEMA = IDC_EVENTS_SCHEMA


def _make_event_row(
    ts: datetime,
    product_id: str = "NO1-QH-0900",
    event_type: str = "new",
    order_id: str = "order-1",
    side: str = "buy",
    price: float = 50.0,
    volume: float = 10.0,
    remaining: float = 10.0,
    aggressor_side: str | None = None,
    trade_id: str | None = None,
) -> dict[str, object]:
    return {
        "timestamp": ts,
        "event_type": event_type,
        "order_id": order_id,
        "zone": "NO1",
        "product_id": product_id,
        "side": side,
        "price_eur_mwh": price,
        "volume_mw": volume,
        "remaining_mw": remaining,
        "aggressor_side": aggressor_side,
        "trade_id": trade_id,
    }


def _write_parquet(path: Path, rows: list[dict[str, object]], rows_per_rg: int) -> None:
    """Write a multi-row-group Parquet file from a list of row dicts."""
    df = pd.DataFrame(rows)
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    table = pa.Table.from_pandas(df, schema=IDC_SCHEMA, preserve_index=False)

    path.parent.mkdir(parents=True, exist_ok=True)
    writer = pq.ParquetWriter(path, schema=IDC_SCHEMA)
    for start in range(0, len(table), rows_per_rg):
        writer.write_table(table.slice(start, rows_per_rg))
    writer.close()


# ---------------------------------------------------------------------------
# Shared fixture path
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "nordpool"


@pytest.fixture
def fixture_parquet_path() -> Path:
    """Pre-generated IDC fixture (generated by tests/generate_idc_fixtures.py)."""
    p = FIXTURE_DIR / "idc_events" / "NO1_2026_03.parquet"
    if not p.exists():
        pytest.skip("IDC fixture not found — run tests/generate_idc_fixtures.py first")
    return p


# ---------------------------------------------------------------------------
# DataManifest tests
# ---------------------------------------------------------------------------


class TestDataManifest:
    def test_missing_directory_raises(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError, match="idc_events"):
            DataManifest(data_dir=tmp_path, zone="NO1")

    def test_builds_from_fixture(self, fixture_parquet_path: Path) -> None:
        manifest = DataManifest(data_dir=FIXTURE_DIR, zone="NO1")
        assert len(manifest.row_groups) > 0

    def test_row_groups_sorted_by_min_timestamp(self, fixture_parquet_path: Path) -> None:
        manifest = DataManifest(data_dir=FIXTURE_DIR, zone="NO1")
        rgs = manifest.row_groups
        for i in range(len(rgs) - 1):
            assert rgs[i].min_timestamp <= rgs[i + 1].min_timestamp

    def test_row_groups_for_range_returns_overlapping(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t0 = datetime(2026, 3, 1, 0, 0, tzinfo=UTC)
        t1 = datetime(2026, 3, 1, 4, 0, tzinfo=UTC)
        t2 = datetime(2026, 3, 1, 8, 0, tzinfo=UTC)
        t3 = datetime(2026, 3, 1, 12, 0, tzinfo=UTC)

        # Two row groups: [t0, t1) and [t2, t3)
        rows_rg1 = [
            _make_event_row(t0, order_id="a"),
            _make_event_row(t1 - timedelta(seconds=1), order_id="b"),
        ]
        rows_rg2 = [
            _make_event_row(t2, order_id="c"),
            _make_event_row(t3 - timedelta(seconds=1), order_id="d"),
        ]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows_rg1 + rows_rg2, rows_per_rg=2)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        assert len(manifest.row_groups) == 2

        # Query range entirely within first RG
        refs = manifest.row_groups_for_range(t0, t0 + timedelta(hours=2))
        assert len(refs) == 1

        # Query range spanning both RGs
        refs = manifest.row_groups_for_range(t0, t3)
        assert len(refs) == 2

        # Query range before any data
        refs = manifest.row_groups_for_range(t0 - timedelta(hours=2), t0 - timedelta(hours=1))
        assert len(refs) == 0

    def test_row_group_ref_fields(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 6, 0, tzinfo=UTC)
        rows = [_make_event_row(t)]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows, rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        ref = manifest.row_groups[0]
        assert isinstance(ref, RowGroupRef)
        assert ref.file_path == path
        assert ref.row_group_index == 0
        assert ref.num_rows == 1
        assert ref.min_timestamp is not None
        assert ref.max_timestamp is not None


# ---------------------------------------------------------------------------
# SlidingWindow tests
# ---------------------------------------------------------------------------


class TestSlidingWindow:
    def test_events_between_yields_correct_range(self, tmp_path: Path) -> None:
        """Events outside the query range must not be yielded."""
        events_dir = tmp_path / "idc_events"
        t_before = datetime(2026, 3, 1, 8, 0, tzinfo=UTC)
        t_inside = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        t_after = datetime(2026, 3, 1, 10, 0, tzinfo=UTC)

        rows = [
            _make_event_row(t_before, order_id="before"),
            _make_event_row(t_inside, order_id="inside"),
            _make_event_row(t_after, order_id="after"),
        ]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows, rows_per_rg=3)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest, lookback=timedelta(hours=4), lookahead=timedelta(hours=1))
        # advance_to t_inside so the row group [t_before, t_after] is within the window
        window.advance_to(t_inside)

        q_start = t_inside - timedelta(minutes=1)
        q_end = t_inside + timedelta(minutes=1)
        events = list(window.events_between(q_start, q_end))
        # "inside" row has timestamp == t_inside which is in [t_inside - 1min, t_inside + 1min)
        assert len(events) == 1

    def test_events_sorted_by_timestamp(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        base = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        rows = [
            _make_event_row(base + timedelta(minutes=2), order_id="c"),
            _make_event_row(base + timedelta(minutes=0), order_id="a"),
            _make_event_row(base + timedelta(minutes=1), order_id="b"),
        ]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows, rows_per_rg=3)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest)
        window.advance_to(base)

        events = list(window.events_between(base, base + timedelta(minutes=5)))
        assert len(events) == 3
        for i in range(len(events) - 1):
            assert events[i].timestamp <= events[i + 1].timestamp

    def test_advance_loads_new_row_groups(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t0 = datetime(2026, 3, 1, 0, 0, tzinfo=UTC)
        t1 = datetime(2026, 3, 1, 6, 0, tzinfo=UTC)

        rows_rg1 = [_make_event_row(t0, order_id="rg1")]
        rows_rg2 = [_make_event_row(t1, order_id="rg2")]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows_rg1 + rows_rg2, rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest, lookback=timedelta(hours=1), lookahead=timedelta(hours=1))

        # At t0 + 30 min, only first RG should be in window
        window.advance_to(t0 + timedelta(minutes=30))
        events_first = list(window.events_between(t0, t0 + timedelta(minutes=30)))
        assert any(isinstance(e, (MarketDataUpdate, HistoricalTrade)) for e in events_first)

        # At t1, second RG should be loaded too
        window.advance_to(t1)
        events_second = list(
            window.events_between(t1 - timedelta(minutes=1), t1 + timedelta(minutes=1))
        )
        assert len(events_second) == 1

    def test_eviction_reduces_memory(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t0 = datetime(2026, 3, 1, 0, 0, tzinfo=UTC)
        t6 = datetime(2026, 3, 1, 6, 0, tzinfo=UTC)
        t12 = datetime(2026, 3, 1, 12, 0, tzinfo=UTC)

        rows = (
            [_make_event_row(t0 + timedelta(minutes=i), order_id=f"rg1-{i}") for i in range(5)]
            + [_make_event_row(t6 + timedelta(minutes=i), order_id=f"rg2-{i}") for i in range(5)]
            + [_make_event_row(t12 + timedelta(minutes=i), order_id=f"rg3-{i}") for i in range(5)]
        )
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows, rows_per_rg=5)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest, lookback=timedelta(hours=1), lookahead=timedelta(hours=1))

        # Load all three row groups
        window.advance_to(t0)
        window.advance_to(t6)
        window.advance_to(t12)
        mem_at_peak = window.memory_usage_bytes

        # Advance far enough to evict first two row groups
        window.advance_to(t12 + timedelta(hours=6))
        mem_after_eviction = window.memory_usage_bytes

        assert mem_after_eviction < mem_at_peak

    def test_memory_usage_bytes_zero_before_advance(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, [_make_event_row(t)], rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest)
        assert window.memory_usage_bytes == 0

    def test_trade_events_yield_historical_trade(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        rows = [
            _make_event_row(
                t,
                event_type="trade",
                order_id="order-1",
                side="buy",
                price=53.10,
                volume=5.0,
                remaining=0.0,
                aggressor_side="sell",
                trade_id="trade-1",
            )
        ]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows, rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest)
        window.advance_to(t)

        events = list(window.events_between(t, t + timedelta(minutes=1)))
        assert len(events) == 1
        evt = events[0]
        assert isinstance(evt, HistoricalTrade)
        assert evt.price_eur_mwh == Decimal("53.1")
        assert evt.aggressor_side == "sell"

    def test_new_events_yield_market_data_update(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        rows = [_make_event_row(t, event_type="new", order_id="o1", side="sell", price=52.0)]
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, rows, rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest)
        window.advance_to(t)

        events = list(window.events_between(t, t + timedelta(minutes=1)))
        assert len(events) == 1
        evt = events[0]
        assert isinstance(evt, MarketDataUpdate)
        assert evt.event_type == "new"
        assert evt.side == "sell"

    def test_events_between_empty_before_advance(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, [_make_event_row(t)], rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(manifest)
        # No advance_to called yet
        events = list(window.events_between(t, t + timedelta(minutes=1)))
        assert events == []

    def test_fixture_parquet_loads_and_yields_events(self, fixture_parquet_path: Path) -> None:
        manifest = DataManifest(data_dir=FIXTURE_DIR, zone="NO1")
        window = SlidingWindow(manifest, lookback=timedelta(hours=4), lookahead=timedelta(hours=1))
        t_start = datetime(2026, 3, 1, 8, 0, tzinfo=UTC)
        window.advance_to(t_start)

        events = list(window.events_between(t_start, t_start + timedelta(hours=1)))
        assert len(events) > 0

        types = {type(e).__name__ for e in events}
        assert "MarketDataUpdate" in types or "HistoricalTrade" in types

    def test_fixture_window_memory_bounded(self, fixture_parquet_path: Path) -> None:
        """Verify memory stays bounded as clock advances through the full day."""
        manifest = DataManifest(data_dir=FIXTURE_DIR, zone="NO1")
        window = SlidingWindow(
            manifest,
            lookback=timedelta(hours=2),
            lookahead=timedelta(minutes=30),
        )

        peak_bytes = 0
        current = datetime(2026, 3, 1, 0, 0, tzinfo=UTC)
        end = datetime(2026, 3, 2, 0, 0, tzinfo=UTC)

        while current < end:
            window.advance_to(current)
            peak_bytes = max(peak_bytes, window.memory_usage_bytes)
            current += timedelta(hours=1)

        # Maximum memory should be bounded to a few row groups (not all 6)
        # Each row group is ~600 rows x ~200 bytes ~= 120 KB; 4 RGs ~= 500 KB
        assert peak_bytes < 5 * 1024 * 1024  # 5 MB upper bound for the tiny fixture

    def test_events_between_no_overlap_returns_empty(self, tmp_path: Path) -> None:
        """events_between with a range that doesn't overlap loaded tables returns nothing."""
        events_dir = tmp_path / "idc_events"
        t_data = datetime(2026, 3, 1, 12, 0, tzinfo=UTC)
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, [_make_event_row(t_data, order_id="o1")], rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        window = SlidingWindow(
            manifest, lookback=timedelta(hours=1), lookahead=timedelta(hours=1)
        )
        window.advance_to(t_data)  # load the row group

        # Query a range entirely before the loaded data
        t_early = datetime(2026, 3, 1, 6, 0, tzinfo=UTC)
        events = list(window.events_between(t_early, t_early + timedelta(minutes=1)))
        assert events == []


# ---------------------------------------------------------------------------
# DataManifest.zone property
# ---------------------------------------------------------------------------


class TestDataManifestZone:
    def test_zone_property(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        path = events_dir / "NO1_2026_03.parquet"
        _write_parquet(path, [_make_event_row(t)], rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="NO1")
        assert manifest.zone == "NO1"

    def test_zone_property_different_zone(self, tmp_path: Path) -> None:
        events_dir = tmp_path / "idc_events"
        t = datetime(2026, 3, 1, 9, 0, tzinfo=UTC)
        path = events_dir / "SE3_2026_03.parquet"
        rows = [_make_event_row(t, order_id="se3-1")]
        _write_parquet(path, rows, rows_per_rg=1)

        manifest = DataManifest(data_dir=tmp_path, zone="SE3")
        assert manifest.zone == "SE3"
